[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v -rxX --tb=long --color=yes --junitxml=build/results.xml --cov-report=xml --cov"
testpaths = [
    "t/",
    "t/test.py",
]

[tool.isort]
profile = "black"
multi_line_output = 3
